### ISSUE TITLE
No such file or directory: /etc/network/if-up.d/scutum_connect

### ISSUE THREAD

**Issue by ghost** [K4YT3X/SCUTUM#1] opened 2017-06-25 10:50 UTC
Error during install:

Which network controller do you want to install for?
1. WICD
2. Network-Manager
3. Both
[?] USER: Please select: 2
[!] WARNING: Installing for network manager
[!] ERROR: [Errno 2] No such file or directory: '/etc/network/if-up.d/scutum_connect'

**Comment by k4yt3x** [comment] 2017-06-29 22:33
This means that the directory '/etc/network/if-up.d/' doesn't exist.
Are you sure that you have NetworkManager installed?
Please tell me if manually creating the directory works if you do have NetworkManager installed already. I will add a make directory command into the code.

### Try this:
~~~~
$ sudo mkdir /etc/network/if-up.d/
~~~~
And then run the installation again.
The error should be gone even if you do NOT have NetworkManager installed. The program should install correctly, but it will not take any effect if you don't have NetworkManager installed since nothing will call the SCUTUM scripts

**Comment by ghost** [comment] 2017-06-30 13:53
Yes, networkmanager 1.8.0 + gnome 3.24 in Arch Linux. There's no /etc/network, only /etc/NetworkManager (inside there's if-up.d)

**Comment by k4yt3x** [comment] 2017-06-30 22:29
~~Oh okay that makes sense. I will add an automatic detection in the installation script then to fix this. Expect it to be done in 10 minutes.~~

I took a look into my folders. I also have the same folders. I think I would need some time to look into Arch linux distribution. However, it's expected to be done by tonight.

**Comment by k4yt3x** [comment] 2017-06-30 23:47
@bryce-lynch The issue is now fixed. Try running the installation again.
Everything should be A-OK by now.

If everything is alright, tell me and I will close this issue

**Comment by ghost** [comment] 2017-07-01 05:44
Installation seems to work now, thanks.
btw you seem to be using "wlan0" for the wireless interface, but Arch is using Systemd's Predictable Network Interface Names (wlp2s0 on my system).

**Comment by k4yt3x** [comment] 2017-07-01 08:31
**Yes that is a problem.** I will look into that and fix that in the next update along with wired interfaces added. I just started projects associated with these territories, so I don't really have much progress yet. **However, thanks for the heads up though.**

~~If you don't mind, you can just **raise a new issue** and I will keep you updated on that.~~

I have already raised a new issue. The problem with interfaces is being fixed in the currently newest version 2.3 alpha. You can try downloading and installing the newest version of SCUTUM. The new installation wizard will guide you through the selection of interfaces. Please try it out to see if it works if you've got time since my PC is having trouble running VMware with an AMD CPU for some reason.

Thanks

PS: I tested it on my machine, and it seems to be just fine.

**Comment by ghost** [comment] 2017-07-01 12:41
Thanks for the quick responses and for fixing the bugs!

**Comment by k4yt3x** [comment] 2017-07-01 20:13
No problem :D

**Closed as completed by k4yt3x** 2017-07-01 20:13 UTC
Labels: bug
